# --- Configuración del Servidor Eureka ---
server:
  port: 8761 # El puerto estándar de la industria para Eureka

# --- Identidad del Servicio ---
spring:
  application:
    name: eureka-server

# --- Configuración de Eureka ---
eureka:
  instance:
    hostname: eureka-server
  client:
    # 1. NO registrarse a sí mismo:
    register-with-eureka: false

    # 2. NO buscar otros servidores:
    fetch-registry: false

    # 3. Define la URL del servicio (para ser usada por los clientes)
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/