server:
  port: 8085

spring:
  application:
    name: servicio-flota
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/tpi_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 0852
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/transporte-realm"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql


servicio:
  tarifa:
    url: http://servicio-tarifa:8083
