# --- Configuración del Servidor ---
server:
  port: 8081

# --- Identidad del Servicio (Spring) ---
spring:
  application:
    name: servicio-cliente

  # --- Configuración de Base de Datos (PostgreSQL) ---
  datasource:
    url: jdbc:postgresql://postgres:5432/tpi_db
    username: postgres
    password: 0852
    driver-class-name: org.postgresql.Driver

  # --- Configuración de JPA (Hibernate) ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-cliente.sql
      data-locations: classpath:data-clientes.sql

  # --- Configuración de Seguridad (Keycloak) ---
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8088/realms/transporte-realm/protocol/openid-connect/certs"


# --- Configuración de Logs ---
logging:
  level:
    org.example.serviciocliente: DEBUG
    org.example.serviciocliente.feign.EnvioFeignCliente: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

# --- Configuración de Swagger (SpringDoc) ---
# Alimenta a OpenAPIConfig.java
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  # Info general de la API
  info:
    title: API de Servicio de Clientes
    version: "1.0.0"
    description: "Microservicio para la gestión y seguimiento de clientes."

servicio:
  envios:
    url: http://servicio-envios:8082


# Configuración de administración de Keycloak (para crear usuarios al registrar clientes)
keycloak:
  admin:
    url: http://keycloak:8080
    username: admin
    password: admin
    client-id: admin-cli
    realm: transporte-realm